# Static stock catalog for US, NSE, and BSE exchanges
# Indian NSE stocks use the '.NS' suffix, and BSE stocks use the '.BO' suffix for yfinance.

STOCK_CATALOG = [
    # --- US STOCKS (NASDAQ/NYSE) ---
    {"symbol": "AAPL", "name": "Apple Inc.", "exchange": "US", "sector": "Technology"},
    {"symbol": "MSFT", "name": "Microsoft Corporation", "exchange": "US", "sector": "Technology"},
    {"symbol": "GOOGL", "name": "Alphabet Inc.", "exchange": "US", "sector": "Technology"},
    {"symbol": "AMZN", "name": "Amazon.com, Inc.", "exchange": "US", "sector": "Consumer Cyclical"},
    {"symbol": "NVDA", "name": "NVIDIA Corporation", "exchange": "US", "sector": "Technology"},
    {"symbol": "TSLA", "name": "Tesla, Inc.", "exchange": "US", "sector": "Consumer Cyclical"},
    {"symbol": "META", "name": "Meta Platforms, Inc.", "exchange": "US", "sector": "Technology"},
    {"symbol": "NFLX", "name": "Netflix, Inc.", "exchange": "US", "sector": "Communication Services"},
    {"symbol": "AMD", "name": "Advanced Micro Devices, Inc.", "exchange": "US", "sector": "Technology"},
    {"symbol": "INTC", "name": "Intel Corporation", "exchange": "US", "sector": "Technology"},
    {"symbol": "QCOM", "name": "QUALCOMM Incorporated", "exchange": "US", "sector": "Technology"},
    {"symbol": "AVGO", "name": "Broadcom Inc.", "exchange": "US", "sector": "Technology"},
    {"symbol": "CSCO", "name": "Cisco Systems, Inc.", "exchange": "US", "sector": "Technology"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "exchange": "US", "sector": "Technology"},
    {"symbol": "CRM", "name": "Salesforce, Inc.", "exchange": "US", "sector": "Technology"},
    {"symbol": "PYPL", "name": "PayPal Holdings, Inc.", "exchange": "US", "sector": "Financial Services"},
    {"symbol": "V", "name": "Visa Inc.", "exchange": "US", "sector": "Financial Services"},
    {"symbol": "MA", "name": "Mastercard Incorporated", "exchange": "US", "sector": "Financial Services"},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co.", "exchange": "US", "sector": "Financial Services"},
    {"symbol": "BAC", "name": "Bank of America Corporation", "exchange": "US", "sector": "Financial Services"},
    {"symbol": "WMT", "name": "Walmart Inc.", "exchange": "US", "sector": "Consumer Defensive"},
    {"symbol": "PG", "name": "Procter & Gamble Company", "exchange": "US", "sector": "Consumer Defensive"},
    {"symbol": "KO", "name": "The Coca-Cola Company", "exchange": "US", "sector": "Consumer Defensive"},
    {"symbol": "PEP", "name": "PepsiCo, Inc.", "exchange": "US", "sector": "Consumer Defensive"},
    {"symbol": "COST", "name": "Costco Wholesale Corporation", "exchange": "US", "sector": "Consumer Defensive"},
    {"symbol": "DIS", "name": "The Walt Disney Company", "exchange": "US", "sector": "Communication Services"},
    {"symbol": "NKE", "name": "NIKE, Inc.", "exchange": "US", "sector": "Consumer Cyclical"},
    {"symbol": "MCD", "name": "McDonald's Corporation", "exchange": "US", "sector": "Consumer Cyclical"},
    {"symbol": "SBUX", "name": "Starbucks Corporation", "exchange": "US", "sector": "Consumer Cyclical"},
    {"symbol": "HD", "name": "The Home Depot, Inc.", "exchange": "US", "sector": "Consumer Cyclical"},
    {"symbol": "XOM", "name": "Exxon Mobil Corporation", "exchange": "US", "sector": "Energy"},
    {"symbol": "CVX", "name": "Chevron Corporation", "exchange": "US", "sector": "Energy"},
    {"symbol": "PFE", "name": "Pfizer Inc.", "exchange": "US", "sector": "Healthcare"},
    {"symbol": "JNJ", "name": "Johnson & Johnson", "exchange": "US", "sector": "Healthcare"},
    {"symbol": "UNH", "name": "UnitedHealth Group Incorporated", "exchange": "US", "sector": "Healthcare"},
    {"symbol": "MRK", "name": "Merck & Co., Inc.", "exchange": "US", "sector": "Healthcare"},
    {"symbol": "ABT", "name": "Abbott Laboratories", "exchange": "US", "sector": "Healthcare"},
    {"symbol": "LLY", "name": "Eli Lilly and Company", "exchange": "US", "sector": "Healthcare"},
    {"symbol": "CAT", "name": "Caterpillar Inc.", "exchange": "US", "sector": "Industrials"},
    {"symbol": "GE", "name": "General Electric Company", "exchange": "US", "sector": "Industrials"},
    {"symbol": "MMM", "name": "3M Company", "exchange": "US", "sector": "Industrials"},
    {"symbol": "HON", "name": "Honeywell International Inc.", "exchange": "US", "sector": "Industrials"},
    {"symbol": "BA", "name": "The Boeing Company", "exchange": "US", "sector": "Industrials"},
    {"symbol": "T", "name": "AT&T Inc.", "exchange": "US", "sector": "Communication Services"},
    {"symbol": "VZ", "name": "Verizon Communications Inc.", "exchange": "US", "sector": "Communication Services"},
    {"symbol": "UPS", "name": "United Parcel Service, Inc.", "exchange": "US", "sector": "Industrials"},
    {"symbol": "FDX", "name": "FedEx Corporation", "exchange": "US", "sector": "Industrials"},
    {"symbol": "GS", "name": "The Goldman Sachs Group, Inc.", "exchange": "US", "sector": "Financial Services"},
    {"symbol": "MS", "name": "Morgan Stanley", "exchange": "US", "sector": "Financial Services"},
    {"symbol": "IBM", "name": "International Business Machines Corporation", "exchange": "US", "sector": "Technology"},

    # --- INDIAN STOCKS (NSE) ---
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries Limited", "exchange": "NSE", "sector": "Energy"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services Limited", "exchange": "NSE", "sector": "Technology"},
    {"symbol": "INFY.NS", "name": "Infosys Limited", "exchange": "NSE", "sector": "Technology"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank Limited", "exchange": "NSE", "sector": "Financial Services"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank Limited", "exchange": "NSE", "sector": "Financial Services"},
    {"symbol": "SBIN.NS", "name": "State Bank of India", "exchange": "NSE", "sector": "Financial Services"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel Limited", "exchange": "NSE", "sector": "Communication Services"},
    {"symbol": "ITC.NS", "name": "ITC Limited", "exchange": "NSE", "sector": "Consumer Defensive"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever Limited", "exchange": "NSE", "sector": "Consumer Defensive"},
    {"symbol": "LTIM.NS", "name": "LTIMindtree Limited", "exchange": "NSE", "sector": "Technology"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro Limited", "exchange": "NSE", "sector": "Industrials"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank Limited", "exchange": "NSE", "sector": "Financial Services"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank Limited", "exchange": "NSE", "sector": "Financial Services"},
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises Limited", "exchange": "NSE", "sector": "Industrials"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports and Special Economic Zone Limited", "exchange": "NSE", "sector": "Industrials"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance Limited", "exchange": "NSE", "sector": "Financial Services"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv Limited", "exchange": "NSE", "sector": "Financial Services"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints Limited", "exchange": "NSE", "sector": "Industrials"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki India Limited", "exchange": "NSE", "sector": "Consumer Cyclical"},
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra Limited", "exchange": "NSE", "sector": "Consumer Cyclical"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors Limited", "exchange": "NSE", "sector": "Consumer Cyclical"},
    {"symbol": "TATASTEEL.NS", "name": "Tata Steel Limited", "exchange": "NSE", "sector": "Basic Materials"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel Limited", "exchange": "NSE", "sector": "Basic Materials"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco Industries Limited", "exchange": "NSE", "sector": "Basic Materials"},
    {"symbol": "COALINDIA.NS", "name": "Coal India Limited", "exchange": "NSE", "sector": "Energy"},
    {"symbol": "NTPC.NS", "name": "NTPC Limited", "exchange": "NSE", "sector": "Utilities"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corporation of India Limited", "exchange": "NSE", "sector": "Utilities"},
    {"symbol": "ONGC.NS", "name": "Oil and Natural Gas Corporation Limited", "exchange": "NSE", "sector": "Energy"},
    {"symbol": "BPCL.NS", "name": "Bharat Petroleum Corporation Limited", "exchange": "NSE", "sector": "Energy"},
    {"symbol": "IOC.NS", "name": "Indian Oil Corporation Limited", "exchange": "NSE", "sector": "Energy"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical Industries Limited", "exchange": "NSE", "sector": "Healthcare"},
    {"symbol": "CIPLA.NS", "name": "Cipla Limited", "exchange": "NSE", "sector": "Healthcare"},
    {"symbol": "DRREDDY.NS", "name": "Dr. Reddy's Laboratories Limited", "exchange": "NSE", "sector": "Healthcare"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals Enterprise Limited", "exchange": "NSE", "sector": "Healthcare"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement Limited", "exchange": "NSE", "sector": "Basic Materials"},
    {"symbol": "GRASIM.NS", "name": "Grasim Industries Limited", "exchange": "NSE", "sector": "Basic Materials"},
    {"symbol": "WIPRO.NS", "name": "Wipro Limited", "exchange": "NSE", "sector": "Technology"},
    {"symbol": "HCLTECH.NS", "name": "HCL Technologies Limited", "exchange": "NSE", "sector": "Technology"},
    {"symbol": "TECHM.NS", "name": "Tech Mahindra Limited", "exchange": "NSE", "sector": "Technology"},
    {"symbol": "NESTLEIND.NS", "name": "Nestle India Limited", "exchange": "NSE", "sector": "Consumer Defensive"},
    {"symbol": "BRITANNIA.NS", "name": "Britannia Industries Limited", "exchange": "NSE", "sector": "Consumer Defensive"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products Limited", "exchange": "NSE", "sector": "Consumer Defensive"},
    {"symbol": "EICHERMOT.NS", "name": "Eicher Motors Limited", "exchange": "NSE", "sector": "Consumer Cyclical"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp Limited", "exchange": "NSE", "sector": "Consumer Cyclical"},
    {"symbol": "TVSMOTOR.NS", "name": "TVS Motor Company Limited", "exchange": "NSE", "sector": "Consumer Cyclical"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank Limited", "exchange": "NSE", "sector": "Financial Services"},
    {"symbol": "HDFCLIFE.NS", "name": "HDFC Life Insurance Company Limited", "exchange": "NSE", "sector": "Financial Services"},
    {"symbol": "SBILIFE.NS", "name": "SBI Life Insurance Company Limited", "exchange": "NSE", "sector": "Financial Services"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto Limited", "exchange": "NSE", "sector": "Consumer Cyclical"},
    {"symbol": "DIVISLAB.NS", "name": "Divi's Laboratories Limited", "exchange": "NSE", "sector": "Healthcare"},

    # --- INDIAN STOCKS (BSE) ---
    {"symbol": "RELIANCE.BO", "name": "Reliance Industries Limited", "exchange": "BSE", "sector": "Energy"},
    {"symbol": "TCS.BO", "name": "Tata Consultancy Services Limited", "exchange": "BSE", "sector": "Technology"},
    {"symbol": "INFY.BO", "name": "Infosys Limited", "exchange": "BSE", "sector": "Technology"},
    {"symbol": "HDFCBANK.BO", "name": "HDFC Bank Limited", "exchange": "BSE", "sector": "Financial Services"},
    {"symbol": "ICICIBANK.BO", "name": "ICICI Bank Limited", "exchange": "BSE", "sector": "Financial Services"},
    {"symbol": "SBIN.BO", "name": "State Bank of India", "exchange": "BSE", "sector": "Financial Services"},
    {"symbol": "BHARTIARTL.BO", "name": "Bharti Airtel Limited", "exchange": "BSE", "sector": "Communication Services"},
    {"symbol": "ITC.BO", "name": "ITC Limited", "exchange": "BSE", "sector": "Consumer Defensive"},
    {"symbol": "HINDUNILVR.BO", "name": "Hindustan Unilever Limited", "exchange": "BSE", "sector": "Consumer Defensive"},
    {"symbol": "L&T.BO", "name": "Larsen & Toubro Limited", "exchange": "BSE", "sector": "Industrials"},
    {"symbol": "AXISBANK.BO", "name": "Axis Bank Limited", "exchange": "BSE", "sector": "Financial Services"},
    {"symbol": "KOTAKBANK.BO", "name": "Kotak Mahindra Bank Limited", "exchange": "BSE", "sector": "Financial Services"},
    {"symbol": "ADANIENT.BO", "name": "Adani Enterprises Limited", "exchange": "BSE", "sector": "Industrials"},
    {"symbol": "BAJFINANCE.BO", "name": "Bajaj Finance Limited", "exchange": "BSE", "sector": "Financial Services"},
    {"symbol": "ASIANPAINT.BO", "name": "Asian Paints Limited", "exchange": "BSE", "sector": "Industrials"},
    {"symbol": "MARUTI.BO", "name": "Maruti Suzuki India Limited", "exchange": "BSE", "sector": "Consumer Cyclical"},
    {"symbol": "M&M.BO", "name": "Mahindra & Mahindra Limited", "exchange": "BSE", "sector": "Consumer Cyclical"},
    {"symbol": "TATAMOTORS.BO", "name": "Tata Motors Limited", "exchange": "BSE", "sector": "Consumer Cyclical"},
    {"symbol": "TATASTEEL.BO", "name": "Tata Steel Limited", "exchange": "BSE", "sector": "Basic Materials"},
    {"symbol": "COALINDIA.BO", "name": "Coal India Limited", "exchange": "BSE", "sector": "Energy"},
    {"symbol": "NTPC.BO", "name": "NTPC Limited", "exchange": "BSE", "sector": "Utilities"},
    {"symbol": "POWERGRID.BO", "name": "Power Grid Corporation of India Limited", "exchange": "BSE", "sector": "Utilities"},
    {"symbol": "ONGC.BO", "name": "Oil and Natural Gas Corporation Limited", "exchange": "BSE", "sector": "Energy"},
    {"symbol": "SUNPHARMA.BO", "name": "Sun Pharmaceutical Industries Limited", "exchange": "BSE", "sector": "Healthcare"},
    {"symbol": "ULTRACEMCO.BO", "name": "UltraTech Cement Limited", "exchange": "BSE", "sector": "Basic Materials"},
    {"symbol": "WIPRO.BO", "name": "Wipro Limited", "exchange": "BSE", "sector": "Technology"},
    {"symbol": "HCLTECH.BO", "name": "HCL Technologies Limited", "exchange": "BSE", "sector": "Technology"},
    {"symbol": "NESTLEIND.BO", "name": "Nestle India Limited", "exchange": "BSE", "sector": "Consumer Defensive"},
    {"symbol": "INDUSINDBK.BO", "name": "IndusInd Bank Limited", "exchange": "BSE", "sector": "Financial Services"},
    {"symbol": "TVSMOTOR.BO", "name": "TVS Motor Company Limited", "exchange": "BSE", "sector": "Consumer Cyclical"},
]
